import type { Metadata } from "next";
import "../sass/style.scss";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }, session: Session) {
  return (
    <html lang="fr">
      <body>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
